### ISSUE TITLE
Tests/MiniProject : incorrect Import in .fsproj

### ISSUE THREAD

**Issue by FZed** [fsprojects/FsLexYacc#31]
The last line of .fsproj file (Import Project="..\..\bin\Debug\FsLexYacc.targets")
refers to Debug directory.
But "PM > Install-Package FsLexYacc" from VS 2013 Community which runs successfully only creates files in packages directory under the project directory.
I followed these steps 
1/ Create a F# console app named "LexAndYaccMiniProject"
2/ Install package
3/ Close solution
4/ Copy all the files (Lexer.fsl, Parser.fsy,Program.fs,LexAndYaccMiniProject.fsproj,App.config) from github to local project directory
5/Open solution
--> Error Message saying there is no such "bin\Debug\FsLexYacc.targets" file.
Thanks for helping me. What did I do wrong and what should I check ?

**Comment by kkm000** [comment]
If you are using the project as base for your own one, just point the import project to the correct location of the `.targets` file pulled by NuGet. They are located in the `bin` directory of the package. This manual fixup is necessary because of #26, which is fixed, but the fix has not been yet released.

**Comment by FZed** [comment]
Thanks @kkm000. You say " just point the import project to the correct location". How do I do that ? I am really willing to make FsLexYacc work in a simple setting (whatever it is) so that I can grow it with my already prepared .fsl and .fsy files. I understand that the port from F# PowerPack to distinct F# github projects needs some time to settle down. Please give me an hint to fix the simplest setting ever that would avoid me MSBUILD and VS proj technical pitfalls that I have no knowledge and experience of.
Regards,
FZed

**Comment by FZed** [comment]
As per FsLexYacc (http://fsprojects.github.io/FsLexYacc/) main page, there is a discrepancy between example files and project files. They link respectively to two different projects on github tests directory, namely : 
- LexAndYaccMiniProject
- TestProjectUsingNugetPackage

which have not the same Import logic in their fsproj file.

It would be greatly appreciated to fix this state even before a template is created as requested by @kkm000 in issue opened today.
I have tried to understand the logic of fsproj Import with no success ; I would like to help but I am clueless (see my detailed attempt below).
Have a great week.

Details : 
My last attempt was to download all FsLexYacc to local directory then open TestProjects solution  with VS 2013 Community.
I get the following error message : 

C:\Users\C\Documents\Visual Studio 2013\Projects\myLexTests\FsLexYacc-master\tests\JsonLexAndYaccExample\JsonLexAndYaccExample.fsproj : error  : The imported project "C:\Users\C\Documents\Visual Studio 2013\Projects\myLexTests\FsLexYacc-master\bin\Debug\FsLexYacc.targets" was not found. 
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\C\Documents\Visual Studio 2013\Projects\myLexTests\FsLexYacc-master\tests\JsonLexAndYaccExample\JsonLexAndYaccExample.fsproj

**Comment by FZed** [comment]
My bad : I did not build FsLexYacc solution properly and went directly to build TestProjects. Now both builds are successful but I had to modify some lines in the .fsproj in the second test project (mini) so that to make it similar to the first one (Json).
Still, @kkm000 initiative to open issue #32 makes a lot of sense.
I close this issue.
Thanks,
FZed

**Comment by kkm000** [comment]
@FZed, you do not actually need to build this whole repository to use FsLex and FsYacc. You can *start* with the test project, just copy it alone into a solution by itself. Then, go ahead and add a NuGet package FsLexYacc (it will also pull some dependencies). After you do that, all necessary binaries and runtimes will be downloaded. Then, open the .fsproj file in any editor (e. g., notepad) and change the path to the .targets file. Find the line which mentions `Debug\FsLexYacc.targets` and change it to look like

```XML
    <Import Project="..\..\packages\FsLexYacc.6.0.4\build\FsLexYacc.targets" />
```
Adjust the number of `..` so that the path corresponds to the location of the file pulled by NuGet.

After you save the `.fsproj` file, VS will reload it. That's all it takes. Reopen if this does not do the trick for you.
